### ISSUE TITLE
Crash when using cells defined in storyboard

### ISSUE THREAD

**Issue by fgeistert** [allaboutapps/DataSource#26]
When using Cells that were defined in storyboard (not in .xib or programmatically) the DataSource crashes. 

We think it has to do with the DataSource trying to register the cell, even though that was already done by the storyboard. 

It is likely caused by a [change](https://github.com/allaboutapps/DataSource/commit/499ad05abc082fe5aba1c8f098c634caba166513#diff-0ce593ba11047d3a69557fc16ed1cfeaR36) introduced in [#24](https://github.com/allaboutapps/DataSource/pull/24).

**Comment by mbuchetics** [comment]
Fix until this is resolved properly: set `registerNibs` to false. You will then also need to register als xibs manually.

**Comment by mbuchetics** [comment]
Fixed in https://github.com/allaboutapps/DataSource/releases/tag/8.0.2 and reverted the auto-registration of call cells. Only xibs and the SeparatorLineCell are registered automatically.
