### ISSUE TITLE
Cartfile missing

### ISSUE THREAD

**Issue by michaelpeternell** [allaboutapps/DataSource#34]
Please add a `Cartfile` to your repository.

The project currently doesn't build with carthage, because carthage cannot detect its dependency on the Differ.framework. carthage uses the `Cartfile` for dependency tracking, it doesn't even look at `Cartfile.resolved`.

This doesn't matter if you have Differ included for other reasons. It also doesn't matter if you have Differ already in your Carthage/Build folder and do a `carthage update`, because `carthage update` doesn't delete obsolete frameworks from the build folder.

To reproduce this isssue, just create a new empty project with just the DataSource dependency built via carthage. The app does not compile.

**Comment by mbuchetics** [comment]
Thanks, I am not sure why we deleted it in the first place. Maybe I thought that SPM dependencies will be built by Xcode anyway. I re-added the file and pushed version `8.1.1`. Can you check if this fixes your issue?

If you delete both, `Cartfile` and `Cartfile.resolved`, does it work then?

**Comment by michaelpeternell** [comment]
The issue is fixed, thanks.

> If you delete both, `Cartfile` and `Cartfile.resolved`, does it work then?

I haven't tried it.
