### ISSUE TITLE
Crash in DataSource+UITableViewDelegate.swift line 471

### ISSUE THREAD

**Issue by michaelpeternell** [allaboutapps/DataSource#35]
I saw a crash in an app of mine, reported via Firebase, in the implementation of `tableView(_:trailingSwipeActionsConfigurationForRowAt:)`.

Affected OS versions: iOS 14.4.1, iOS 14.4.2, iOS 14.5.1, iOS 14.6.0
Affected DataSource version: 8.1.1
Affected Phones: iPhone 7, iPhone 8, iPhone 11, iPhone 11 Pro, iPhone 12, iPhone XR, iPhone SE2
Xcode version used: 12.4

![Bildschirmfoto 2021-06-15 um 11 32 37](https://user-images.githubusercontent.com/5628066/122029926-9cf19580-cdcd-11eb-9868-a9b648b7fae0.png)

In the end, the crash lies in `IndexPath.section.getter`, and [an Apple employee explains](https://developer.apple.com/forums/thread/663787) that this happens because `IndexPath.indices.count != 2`.

Unfortunately, I can't reproduce the crash and it happens rarely, and I only know about it because of crash reporting. I don't know if it is an iOS bug, a bug in my app, or a bug in DataSource, but I think it can be fixed by adding a safety check to DataSource.

## The problem

`DataSource.tableView(_:trailingSwipeActionsConfigurationForRowAt:)` is called with a bad indexPath that doesn't have two indices (i.e. `indexPath.indices.count != 2`. But all IndexPath values that are used for a table view should have exactly 2 indices: the "section" and the "row".)
The line `let cellDescriptor = self.cellDescriptor(at: indexPath) as? CellDescriptorTypeiOS11` is therefore called with a bad IndexPath.
That method calls `DataSource.visibleRow(at:)`, which is implemented as `visibleSections[indexPath.section].visibleRow(at: indexPath.row)`. And that crashes because `indexPath.section` crashes.

## Possible solution

I would suggest to add a safety check to `DataSource.tableView(_:trailingSwipeActionsConfigurationForRowAt:)` and `DataSource.tableView(_:leadingSwipeActionsConfigurationForRowAt:)` like this:

    if indexPath.indices.count != 2 {
        return nil
    }

because if indexPath.indices.count is not 2, the next line will crash deterministically.

---

(I could create a pull request if you want)

**Comment by mbuchetics** [comment]
Thank you Michael for the detailed bug report. That's a weird issue! PRs are always welcome, so feel free to submit one 😉
